
version: '2.1'
services:
  #docker-compose build image
  image:
    build:
      context: image
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER}
      #- IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://fileserver.infra.top}
      - IMAGE_ARG_NODE_VERSION=${IMAGE_ARG_NODE_VERSION:-10.15.3}
      - IMAGE_ARG_NVM_VERSION=${IMAGE_ARG_NVM_VERSION:-0.34.0}
      - IMAGE_ARG_NVM_NODEJS_ORG_MIRROR=${IMAGE_ARG_NVM_NODEJS_ORG_MIRROR:-https://npm.taobao.org/mirrors/node}
      - IMAGE_ARG_NVM_IOJS_ORG_MIRROR=${IMAGE_ARG_NVM_IOJS_ORG_MIRROR:-https://npm.taobao.org/mirrors/iojs}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-nvm-node}:${IMAGE_TAG:-10.15.3-bionic}
  #docker-compose build dumper
  dumper:
    build:
      context: dumper
      dockerfile: Dockerfile_dumper
    image: tmp/dumper:latest
  #docker-compose build archive
  archive:
    build:
      context: .
      dockerfile: Dockerfile_archive
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-nvm-node}:${IMAGE_TAG:-10.15.3-bionic}-archive
